### ISSUE TITLE
low severity führt zu einem Fehler

### ISSUE THREAD

**Issue by ankri** [tangro/actions-audit#2]
Ein Low Severity Audit sollte den Build nicht fehlschlagen lassen

**Comment by Orangen** [comment]
@ankri  Vielleicht habe ich das behoben. wenn du diesen meintest

![image](https://user-images.githubusercontent.com/5445259/84264762-0c310b80-ab22-11ea-90ec-5481fcb90e6d.png)

es gibt jetzt keine throw error mehr wenn audit zurückliefert das updates nötig sind.
aber die Ausgabe ist immer noch das rote X.

**Comment by ankri** [comment]
scheint gefixt zu sein 👍
