### ISSUE TITLE
Breaking changes im audit json Format ab npm v7

### ISSUE THREAD

**Issue by Orangen** [tangro/actions-audit#20]
In Node 16 hat das Json result eine andere Struktur damit klappt die anzeige nicht mehr.
für Node14 muss es noch geprüft werden.

**Comment by clausreinke** [comment]
laut diesem (etwas aufgeregten;-) post kamen die Änderungen in npm v7: https://uko.codes/dealing-with-npm-v7-audit-changes

**Comment by Orangen** [comment]
das neue Json enthält leider viel weniger informationen.
Aber die die noch da sind werden wieder angezeigt 
![image](https://user-images.githubusercontent.com/5445259/161266545-628ce1a3-c0df-49bd-a2ba-1f0a8ca8bc28.png)
